[build-system]
requires = ["setuptools"]

[project]
name = "aiteach-api-utils"  # Replace with your desired package name
version = "0.1.0"
description = "A Python package for configuration management with TOML"
dependencies = []  # No external dependencies in this example
requires-python = ">=3.7"