[build-system]
requires = ["setuptools"]

[project]
name = "aiteach_api_utils" 
version = "0.1.3"
description = "A Python package for configuration management with TOML"
dependencies = []  # No external dependencies in this example
requires-python = ">=3.7"